language: python
matrix:
  include:
    - python: 3.5
      env:
      - TOX_ENV=lint
    - python: 3.5
      env:
      - TOX_ENV=py27
    - python: 3.5
      env:
      - TOX_ENV=py34
    - python: 3.5
      env:
      - TOX_ENV=py35
    - python: 3.6
      env:
      - TOX_ENV=py36
    - python: pypy
      env:
      - TOX_ENV=pypy
    - python: pypy3.5-5.8.0
      env:
      - TOX_ENV=pypy3
  allow_failures:
    - python: pypy3.5-5.8.0
      env:
      - TOX_ENV=pypy3
    - python: 3.5
      env:
      - TOX_ENV=jython
  fast_finish: true
install:
  - travis_retry pip install tox
before_script:
  - export JYTHON_URL='http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar'
  - if [ $TOX_ENV = "jython" ]; then wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; export PATH=$HOME/jython/bin:$PATH; fi
script:
  - tox -e $TOX_ENV
after_success:
  - bash <(curl -s https://codecov.io/bash)
